### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by nicosammito** [code0-tech/sagittarius#121]
In extension to the current role implementation we need the following:

- [x] Update role mutation (#123)
- [x] Delete role mutation (#125)
- [x] Role type to organisation for query roles (#124)
