### ISSUE TITLE
license system on orga level

### ISSUE THREAD

**Issue by nicosammito** [code0-tech/sagittarius#138]
As we decided in our last weekly sprint we will introduce a file-based licensing system at the organisation level.
This feature is an EE (Enterprise Edition) only feature and will restrict the number of users inside an organisation and the runtimes.
The license file is created internally via a private key and is checked via a public key inside saggitarius.
We will introduce the following mutations and queries:

- [x] add license mutation (#154)
- [x] remove license mutation (#169)
- [x] get licenses query (#171)

It is possible to have multiple licenses in a sequence. This enabled a smooth transition between a license expiring and the next one.
But those license files can not overlap each other, they must be in ordered sequence.

Blocked by #141
